using Insurance.InventoryService.Endpoints.Api;
using Insurance.InventoryService.Infra.Persistence.RDB.Commands;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);
var app = builder.ConfigureServices().ConfigurePipeline();

// Intentional no-op marker so API image rebuilds are easy to detect in source diffs.
// Inventory API bootstrap intentionally stays thin; service wiring lives in Hosting.cs.
// Deployment marker: inventory API image rebuild trigger.
using (var scope = app.Services.CreateScope())
{
    try
    {
        var commandDbContext = scope.ServiceProvider.GetRequiredService<InventoryServiceCommandDbContext>();
        commandDbContext.Database.EnsureCreated();
        commandDbContext.Database.ExecuteSqlRaw("""
            ALTER TABLE IF EXISTS "CategoryAttributeRules" ADD COLUMN IF NOT EXISTS "IsVariantCodeCovered" BOOLEAN NOT NULL DEFAULT FALSE;
            ALTER TABLE IF EXISTS "Categories" ADD COLUMN IF NOT EXISTS "ImageFileKey" TEXT NULL;
            ALTER TABLE IF EXISTS "Categories" ADD COLUMN IF NOT EXISTS "ImageUrl" TEXT NULL;
            ALTER TABLE IF EXISTS "Categories" ADD COLUMN IF NOT EXISTS "ImageThumbnailUrl" TEXT NULL;
            ALTER TABLE IF EXISTS "Products" ADD COLUMN IF NOT EXISTS "ImageFileKey" TEXT NULL;
            ALTER TABLE IF EXISTS "Products" ADD COLUMN IF NOT EXISTS "ImageUrl" TEXT NULL;
            ALTER TABLE IF EXISTS "Products" ADD COLUMN IF NOT EXISTS "ImageThumbnailUrl" TEXT NULL;

            CREATE TABLE IF NOT EXISTS "VariantImages" (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "VariantRef" UUID NOT NULL,
                "FileKey" TEXT NOT NULL,
                "OriginalFileName" TEXT NOT NULL,
                "ContentType" TEXT NOT NULL,
                "OriginalUrl" TEXT NOT NULL,
                "ThumbnailUrl" TEXT NOT NULL,
                "DisplayOrder" INTEGER NOT NULL,
                "IsPrimary" BOOLEAN NOT NULL
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_VariantImages_VariantRef_FileKey" ON "VariantImages" ("VariantRef", "FileKey");

            CREATE TABLE IF NOT EXISTS "PriceTypes" (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "BusinessKey" UUID NOT NULL,
                "Code" TEXT NOT NULL,
                "Name" TEXT NOT NULL,
                "IsActive" BOOLEAN NOT NULL
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_PriceTypes_BusinessKey" ON "PriceTypes" ("BusinessKey");
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_PriceTypes_Code" ON "PriceTypes" ("Code");

            CREATE TABLE IF NOT EXISTS "CategoryVariantNameFormulas" (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "BusinessKey" UUID NOT NULL,
                "CategoryRef" UUID NOT NULL,
                "Name" TEXT NOT NULL,
                "Separator" TEXT NOT NULL,
                "DisplayOrder" INTEGER NOT NULL,
                "IsActive" BOOLEAN NOT NULL
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_CategoryVariantNameFormulas_BusinessKey" ON "CategoryVariantNameFormulas" ("BusinessKey");
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_CategoryVariantNameFormulas_CategoryRef_Name" ON "CategoryVariantNameFormulas" ("CategoryRef", "Name");

            CREATE TABLE IF NOT EXISTS "CategoryVariantNameFormulaParts" (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "BusinessKey" UUID NOT NULL,
                "FormulaRef" UUID NOT NULL,
                "AttributeRef" UUID NOT NULL,
                "SortOrder" INTEGER NOT NULL
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_CategoryVariantNameFormulaParts_BusinessKey" ON "CategoryVariantNameFormulaParts" ("BusinessKey");
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_CategoryVariantNameFormulaParts_FormulaRef_SortOrder" ON "CategoryVariantNameFormulaParts" ("FormulaRef", "SortOrder");
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_CategoryVariantNameFormulaParts_FormulaRef_AttributeRef" ON "CategoryVariantNameFormulaParts" ("FormulaRef", "AttributeRef");

            CREATE TABLE IF NOT EXISTS "PriceChannels" (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "BusinessKey" UUID NOT NULL,
                "Code" TEXT NOT NULL,
                "Name" TEXT NOT NULL,
                "IsActive" BOOLEAN NOT NULL
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_PriceChannels_BusinessKey" ON "PriceChannels" ("BusinessKey");
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_PriceChannels_Code" ON "PriceChannels" ("Code");

            CREATE TABLE IF NOT EXISTS "SellerVariantPrices" (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "BusinessKey" UUID NOT NULL,
                "SellerRef" UUID NOT NULL,
                "VariantRef" UUID NOT NULL,
                "PriceTypeRef" UUID NOT NULL,
                "PriceChannelRef" UUID NOT NULL,
                "Amount" NUMERIC NOT NULL,
                "Currency" TEXT NOT NULL,
                "MinQty" NUMERIC NOT NULL,
                "Priority" INTEGER NOT NULL,
                "EffectiveFrom" TIMESTAMP WITHOUT TIME ZONE NULL,
                "EffectiveTo" TIMESTAMP WITHOUT TIME ZONE NULL,
                "IsActive" BOOLEAN NOT NULL
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_SellerVariantPrices_BusinessKey" ON "SellerVariantPrices" ("BusinessKey");
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_SellerVariantPrices_Key" ON "SellerVariantPrices" ("SellerRef", "VariantRef", "PriceTypeRef", "PriceChannelRef");
            CREATE INDEX IF NOT EXISTS "IX_SellerVariantPrices_SellerRef" ON "SellerVariantPrices" ("SellerRef");
            CREATE INDEX IF NOT EXISTS "IX_SellerVariantPrices_VariantRef" ON "SellerVariantPrices" ("VariantRef");

            CREATE TABLE IF NOT EXISTS "Offers" (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "BusinessKey" UUID NOT NULL,
                "PriceRef" UUID NOT NULL,
                "Name" TEXT NOT NULL,
                "DiscountAmount" NUMERIC NULL,
                "DiscountPercent" NUMERIC NULL,
                "MaxQuantity" NUMERIC NULL,
                "Priority" INTEGER NOT NULL,
                "StartAt" TIMESTAMP WITHOUT TIME ZONE NULL,
                "EndAt" TIMESTAMP WITHOUT TIME ZONE NULL,
                "IsActive" BOOLEAN NOT NULL,
                "SellerVariantPriceId" BIGINT NULL
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Offers_BusinessKey" ON "Offers" ("BusinessKey");
            CREATE INDEX IF NOT EXISTS "IX_Offers_PriceRef" ON "Offers" ("PriceRef");
            CREATE INDEX IF NOT EXISTS "IX_Offers_SellerVariantPriceId" ON "Offers" ("SellerVariantPriceId");
            """);
    }
    catch (Exception ex)
    {
        var logger = scope.ServiceProvider.GetRequiredService<ILoggerFactory>().CreateLogger("InventoryService.Startup");
        logger.LogError(ex, "An error occurred while initializing InventoryService database.");
    }
}

app.Run();
