START TRANSACTION;
ALTER TABLE "Users" ADD "CreatedByOrganizationBusinessKey" character varying(50);

ALTER TABLE "Users" ADD "CreatedByPersonaBusinessKey" character varying(50);

ALTER TABLE "Users" ADD "ModifiedByOrganizationBusinessKey" character varying(50);

ALTER TABLE "Users" ADD "ModifiedByPersonaBusinessKey" character varying(50);

ALTER TABLE "UserRoleAssignments" ADD "CreatedByOrganizationBusinessKey" character varying(50);

ALTER TABLE "UserRoleAssignments" ADD "CreatedByPersonaBusinessKey" character varying(50);

ALTER TABLE "UserRoleAssignments" ADD "ModifiedByOrganizationBusinessKey" character varying(50);

ALTER TABLE "UserRoleAssignments" ADD "ModifiedByPersonaBusinessKey" character varying(50);

ALTER TABLE "RolePermissions" ADD "CreatedByOrganizationBusinessKey" character varying(50);

ALTER TABLE "RolePermissions" ADD "CreatedByPersonaBusinessKey" character varying(50);

ALTER TABLE "RolePermissions" ADD "ModifiedByOrganizationBusinessKey" character varying(50);

ALTER TABLE "RolePermissions" ADD "ModifiedByPersonaBusinessKey" character varying(50);

ALTER TABLE "Permissions" ADD "CreatedByOrganizationBusinessKey" character varying(50);

ALTER TABLE "Permissions" ADD "CreatedByPersonaBusinessKey" character varying(50);

ALTER TABLE "Permissions" ADD "ModifiedByOrganizationBusinessKey" character varying(50);

ALTER TABLE "Permissions" ADD "ModifiedByPersonaBusinessKey" character varying(50);

ALTER TABLE "Organizations" ADD "CreatedByOrganizationBusinessKey" character varying(50);

ALTER TABLE "Organizations" ADD "CreatedByPersonaBusinessKey" character varying(50);

ALTER TABLE "Organizations" ADD "ModifiedByOrganizationBusinessKey" character varying(50);

ALTER TABLE "Organizations" ADD "ModifiedByPersonaBusinessKey" character varying(50);

ALTER TABLE "Memberships" ADD "CreatedByOrganizationBusinessKey" character varying(50);

ALTER TABLE "Memberships" ADD "CreatedByPersonaBusinessKey" character varying(50);

ALTER TABLE "Memberships" ADD "ModifiedByOrganizationBusinessKey" character varying(50);

ALTER TABLE "Memberships" ADD "ModifiedByPersonaBusinessKey" character varying(50);

CREATE TABLE "OtpCodes" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "MobileNumber" character varying(32),
    "Code" character varying(16) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "IsVerified" boolean NOT NULL,
    "Attempts" integer NOT NULL,
    "Status" smallint NOT NULL,
    "CreatedByOrganizationBusinessKey" character varying(50),
    "CreatedByPersonaBusinessKey" character varying(50),
    "CreatedByUserId" character varying(50),
    "CreatedDateTime" timestamp with time zone,
    "ModifiedByOrganizationBusinessKey" character varying(50),
    "ModifiedByPersonaBusinessKey" character varying(50),
    "ModifiedByUserId" character varying(50),
    "ModifiedDateTime" timestamp with time zone,
    "BusinessKey" uuid NOT NULL,
    CONSTRAINT "PK_OtpCodes" PRIMARY KEY ("Id")
);

CREATE TABLE "Tenants" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" text NOT NULL,
    "OrganizationBusinessKey" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedByOrganizationBusinessKey" character varying(50),
    "CreatedByPersonaBusinessKey" character varying(50),
    "CreatedByUserId" character varying(50),
    "CreatedDateTime" timestamp with time zone,
    "ModifiedByOrganizationBusinessKey" character varying(50),
    "ModifiedByPersonaBusinessKey" character varying(50),
    "ModifiedByUserId" character varying(50),
    "ModifiedDateTime" timestamp with time zone,
    "BusinessKey" uuid NOT NULL,
    CONSTRAINT "PK_Tenants" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_OtpCodes_CreatedAt" ON "OtpCodes" ("CreatedAt");

CREATE INDEX "IX_OtpCodes_MobileNumber" ON "OtpCodes" ("MobileNumber");

CREATE INDEX "IX_Tenants_OrganizationBusinessKey" ON "Tenants" ("OrganizationBusinessKey");

CREATE UNIQUE INDEX "IX_Tenants_TenantId" ON "Tenants" ("TenantId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260513054416_AddTenants', '9.0.11');

COMMIT;

