WITH permission_seed("Code", "Title", "Module", "Type", "Scope", "Description") AS (
    VALUES
    ('Dashboard.Home.View', 'View dashboard home', 'Dashboard.Home', 1, 3, 'UI page permission'),
    ('Dashboard.People.View', 'View people management', 'Dashboard.People', 1, 3, 'UI page permission'),
    ('Dashboard.Catalog.Categories.View', 'View category management page', 'Dashboard.Catalog', 1, 3, 'UI page permission'),
    ('Dashboard.Catalog.Products.View', 'View product management page', 'Dashboard.Catalog', 1, 3, 'UI page permission'),
    ('Dashboard.Catalog.Variants.View', 'View variant management page', 'Dashboard.Catalog', 1, 3, 'UI page permission'),
    ('Dashboard.Inventory.Warehouses.View', 'View warehouse management page', 'Dashboard.Inventory', 1, 3, 'UI page permission'),
    ('Dashboard.Inventory.Documents.View', 'View inventory documents page', 'Dashboard.Inventory', 1, 3, 'UI page permission'),
    ('Dashboard.Pricing.View', 'View pricing page', 'Dashboard.Pricing', 1, 3, 'UI page permission'),
    ('Dashboard.Invoice.View', 'View invoice page', 'Dashboard.Invoice', 1, 3, 'UI page permission'),

    ('Auth.Register', 'Register user', 'User.Auth', 4, 1, 'User service API permission'),
    ('User.Create', 'Create user', 'User.User', 4, 1, 'User service API permission'),
    ('Organization.Create', 'Create organization', 'User.Organization', 4, 1, 'User service API permission'),
    ('Organization.GetAll', 'View organizations', 'User.Organization', 4, 1, 'User service API permission'),
    ('Membership.Create', 'Create membership', 'User.Membership', 4, 1, 'User service API permission'),
    ('Membership.AssignRole', 'Assign role to membership', 'User.Membership', 4, 1, 'User service API permission'),
    ('Role.Create', 'Create role', 'User.Role', 4, 1, 'User service API permission'),
    ('Role.AssignPermission', 'Assign permission to role', 'User.Role', 4, 1, 'User service API permission'),
    ('Role.RemovePermission', 'Remove permission from role', 'User.Role', 4, 1, 'User service API permission'),
    ('Permission.Create.System', 'Create system permission', 'User.Permission', 4, 1, 'User service API permission'),
    ('Permission.Create.Organization', 'Create organization permission', 'User.Permission', 4, 1, 'User service API permission'),
    ('Permission.Create.Application', 'Create application permission', 'User.Permission', 4, 1, 'User service API permission'),

    ('Catalog.Category.View', 'View categories', 'Catalog.Category', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Category.Create', 'Create category', 'Catalog.Category', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Category.Update', 'Update category', 'Catalog.Category', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Category.Move', 'Move category', 'Catalog.Category', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Category.Activate', 'Activate category', 'Catalog.Category', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Category.Deactivate', 'Deactivate category', 'Catalog.Category', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Category.Delete', 'Delete category', 'Catalog.Category', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Category.Rule.Assign', 'Assign category attribute rule', 'Catalog.Category', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Category.Rule.Update', 'Update category attribute rule', 'Catalog.Category', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Category.Rule.Activate', 'Activate category attribute rule', 'Catalog.Category', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Category.Rule.Deactivate', 'Deactivate category attribute rule', 'Catalog.Category', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Category.Rule.Remove', 'Remove category attribute rule', 'Catalog.Category', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Category.Formula.Manage', 'Manage category variant name formula', 'Catalog.Category', 4, 3, 'Inventory API/UI permission'),

    ('Catalog.AttributeDefinition.View', 'View attribute definitions', 'Catalog.AttributeDefinition', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.AttributeDefinition.Create', 'Create attribute definition', 'Catalog.AttributeDefinition', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.AttributeDefinition.Update', 'Update attribute definition', 'Catalog.AttributeDefinition', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.AttributeDefinition.Activate', 'Activate attribute definition', 'Catalog.AttributeDefinition', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.AttributeDefinition.Deactivate', 'Deactivate attribute definition', 'Catalog.AttributeDefinition', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.AttributeDefinition.Delete', 'Delete attribute definition', 'Catalog.AttributeDefinition', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.AttributeOption.View', 'View attribute options', 'Catalog.AttributeOption', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.AttributeOption.Create', 'Create attribute option', 'Catalog.AttributeOption', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.AttributeOption.Update', 'Update attribute option', 'Catalog.AttributeOption', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.AttributeOption.Activate', 'Activate attribute option', 'Catalog.AttributeOption', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.AttributeOption.Deactivate', 'Deactivate attribute option', 'Catalog.AttributeOption', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.AttributeOption.Delete', 'Delete attribute option', 'Catalog.AttributeOption', 4, 3, 'Inventory API/UI permission'),

    ('Catalog.Product.View', 'View products', 'Catalog.Product', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Product.Create', 'Create product', 'Catalog.Product', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Product.Update', 'Update product', 'Catalog.Product', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Product.Activate', 'Activate product', 'Catalog.Product', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Product.Deactivate', 'Deactivate product', 'Catalog.Product', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Product.Delete', 'Delete product', 'Catalog.Product', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Product.ChangeCategory', 'Change product category', 'Catalog.Product', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.ProductAttributeValue.Set', 'Set product attribute value', 'Catalog.Product', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.ProductAttributeValue.Remove', 'Remove product attribute value', 'Catalog.Product', 4, 3, 'Inventory API/UI permission'),

    ('Catalog.Variant.View', 'View variants', 'Catalog.Variant', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Variant.Create', 'Create variant', 'Catalog.Variant', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Variant.Update', 'Update variant', 'Catalog.Variant', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Variant.Activate', 'Activate variant', 'Catalog.Variant', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Variant.Deactivate', 'Deactivate variant', 'Catalog.Variant', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Variant.Delete', 'Delete variant', 'Catalog.Variant', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Variant.ChangeTrackingPolicy', 'Change variant tracking policy', 'Catalog.Variant', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Variant.ChangeBaseUom', 'Change variant base unit of measure', 'Catalog.Variant', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.Variant.LockInventoryMovement', 'Lock variant inventory movement', 'Catalog.Variant', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.VariantAttributeValue.Set', 'Set variant attribute value', 'Catalog.Variant', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.VariantAttributeValue.Remove', 'Remove variant attribute value', 'Catalog.Variant', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.VariantUomConversion.Upsert', 'Upsert variant UOM conversion', 'Catalog.Variant', 4, 3, 'Inventory API/UI permission'),
    ('Catalog.VariantUomConversion.Remove', 'Remove variant UOM conversion', 'Catalog.Variant', 4, 3, 'Inventory API/UI permission'),

    ('Inventory.Category.Create', 'Create category API alias', 'Inventory.Category', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.Category.Update', 'Update category API alias', 'Inventory.Category', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.Category.Move', 'Move category API alias', 'Inventory.Category', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.Category.Delete', 'Delete category API alias', 'Inventory.Category', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.CategoryAttributeRule.Assign', 'Assign category attribute rule API alias', 'Inventory.Category', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.CategoryAttributeRule.Update', 'Update category attribute rule API alias', 'Inventory.Category', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.CategoryAttributeRule.Remove', 'Remove category attribute rule API alias', 'Inventory.Category', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.CategoryVariantNameFormula.Manage', 'Manage category variant name formula API alias', 'Inventory.Category', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.Product.Read', 'Read product API alias', 'Inventory.Product', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.Product.Create', 'Create product API alias', 'Inventory.Product', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.Product.Update', 'Update product API alias', 'Inventory.Product', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.Product.Delete', 'Delete product API alias', 'Inventory.Product', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.Product.ChangeCategory', 'Change product category API alias', 'Inventory.Product', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.ProductAttributeValue.Set', 'Set product attribute value API alias', 'Inventory.Product', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.ProductAttributeValue.Remove', 'Remove product attribute value API alias', 'Inventory.Product', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.ProductVariant.Read', 'Read variant API alias', 'Inventory.ProductVariant', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.ProductVariant.Create', 'Create variant API alias', 'Inventory.ProductVariant', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.ProductVariant.Update', 'Update variant API alias', 'Inventory.ProductVariant', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.ProductVariant.Delete', 'Delete variant API alias', 'Inventory.ProductVariant', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.ProductVariant.ChangeTrackingPolicy', 'Change variant tracking policy API alias', 'Inventory.ProductVariant', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.ProductVariant.ChangeBaseUom', 'Change variant base UOM API alias', 'Inventory.ProductVariant', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.ProductVariant.LockInventoryMovement', 'Lock variant inventory movement API alias', 'Inventory.ProductVariant', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.ProductVariantUomConversion.Upsert', 'Upsert variant UOM conversion API alias', 'Inventory.ProductVariant', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.ProductVariantUomConversion.Remove', 'Remove variant UOM conversion API alias', 'Inventory.ProductVariant', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.VariantAttributeValue.Set', 'Set variant attribute value API alias', 'Inventory.ProductVariant', 4, 3, 'Inventory API compatibility alias'),
    ('Inventory.VariantAttributeValue.Remove', 'Remove variant attribute value API alias', 'Inventory.ProductVariant', 4, 3, 'Inventory API compatibility alias'),

    ('Inventory.Warehouse.View', 'View warehouses', 'Inventory.Warehouse', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.Warehouse.Create', 'Create warehouse', 'Inventory.Warehouse', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.Warehouse.Update', 'Update warehouse', 'Inventory.Warehouse', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.Warehouse.Activate', 'Activate warehouse', 'Inventory.Warehouse', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.Warehouse.Deactivate', 'Deactivate warehouse', 'Inventory.Warehouse', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.Warehouse.Delete', 'Delete warehouse', 'Inventory.Warehouse', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.Location.View', 'View locations', 'Inventory.Location', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.Location.Create', 'Create location', 'Inventory.Location', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.Location.Update', 'Update location', 'Inventory.Location', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.Location.Activate', 'Activate location', 'Inventory.Location', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.Location.Deactivate', 'Deactivate location', 'Inventory.Location', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.Location.Delete', 'Delete location', 'Inventory.Location', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.QualityStatus.View', 'View quality statuses', 'Inventory.QualityStatus', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.QualityStatus.Create', 'Create quality status', 'Inventory.QualityStatus', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.QualityStatus.Update', 'Update quality status', 'Inventory.QualityStatus', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.QualityStatus.Activate', 'Activate quality status', 'Inventory.QualityStatus', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.QualityStatus.Deactivate', 'Deactivate quality status', 'Inventory.QualityStatus', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.QualityStatus.Delete', 'Delete quality status', 'Inventory.QualityStatus', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.UnitOfMeasure.View', 'View units of measure', 'Inventory.UnitOfMeasure', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.UnitOfMeasure.Create', 'Create unit of measure', 'Inventory.UnitOfMeasure', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.UnitOfMeasure.Update', 'Update unit of measure', 'Inventory.UnitOfMeasure', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.UnitOfMeasure.Activate', 'Activate unit of measure', 'Inventory.UnitOfMeasure', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.UnitOfMeasure.Deactivate', 'Deactivate unit of measure', 'Inventory.UnitOfMeasure', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.UnitOfMeasure.Delete', 'Delete unit of measure', 'Inventory.UnitOfMeasure', 4, 3, 'Inventory API/UI permission'),

    ('Inventory.Document.View', 'View inventory documents', 'Inventory.Document', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.Document.Search', 'Search inventory documents', 'Inventory.Document', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.Document.Create', 'Create inventory document', 'Inventory.Document', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.Document.Approve', 'Approve inventory document', 'Inventory.Document', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.Document.Reject', 'Reject inventory document', 'Inventory.Document', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.Document.Cancel', 'Cancel inventory document', 'Inventory.Document', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.Document.Post', 'Post inventory document', 'Inventory.Document', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.Transaction.View', 'View inventory transactions', 'Inventory.Transaction', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.StockDetail.View', 'View stock details', 'Inventory.StockDetail', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.StockDetail.Manage', 'Manage stock details', 'Inventory.StockDetail', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.SourceBalance.View', 'View source balances', 'Inventory.SourceBalance', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.SourceBalance.Manage', 'Manage source balances', 'Inventory.SourceBalance', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.Reservation.View', 'View reservations', 'Inventory.Reservation', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.Reservation.Manage', 'Manage reservations', 'Inventory.Reservation', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.SerialItem.View', 'View serial items', 'Inventory.SerialItem', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.SerialItem.Manage', 'Manage serial items', 'Inventory.SerialItem', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.ReturnRequest.View', 'View return requests', 'Inventory.ReturnRequest', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.ReturnRequest.Manage', 'Manage return requests', 'Inventory.ReturnRequest', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.Fulfillment.View', 'View fulfillments', 'Inventory.Fulfillment', 4, 3, 'Inventory API/UI permission'),
    ('Inventory.Fulfillment.Manage', 'Manage fulfillments', 'Inventory.Fulfillment', 4, 3, 'Inventory API/UI permission'),

    ('Pricing.PriceChannel.View', 'View price channels', 'Pricing.PriceChannel', 4, 3, 'Inventory API/UI permission'),
    ('Pricing.PriceChannel.Create', 'Create price channel', 'Pricing.PriceChannel', 4, 3, 'Inventory API/UI permission'),
    ('Pricing.PriceChannel.Update', 'Update price channel', 'Pricing.PriceChannel', 4, 3, 'Inventory API/UI permission'),
    ('Pricing.PriceType.View', 'View price types', 'Pricing.PriceType', 4, 3, 'Inventory API/UI permission'),
    ('Pricing.PriceType.Create', 'Create price type', 'Pricing.PriceType', 4, 3, 'Inventory API/UI permission'),
    ('Pricing.PriceType.Update', 'Update price type', 'Pricing.PriceType', 4, 3, 'Inventory API/UI permission'),
    ('Pricing.Seller.View', 'View sellers', 'Pricing.Seller', 4, 3, 'Inventory API/UI permission'),
    ('Pricing.Seller.Create', 'Create seller', 'Pricing.Seller', 4, 3, 'Inventory API/UI permission'),
    ('Pricing.Seller.Update', 'Update seller', 'Pricing.Seller', 4, 3, 'Inventory API/UI permission'),
    ('Pricing.Seller.Delete', 'Delete seller', 'Pricing.Seller', 4, 3, 'Inventory API/UI permission'),
    ('Pricing.SellerVariantPrice.View', 'View seller variant prices', 'Pricing.SellerVariantPrice', 4, 3, 'Inventory API/UI permission'),
    ('Pricing.SellerVariantPrice.Create', 'Create seller variant price', 'Pricing.SellerVariantPrice', 4, 3, 'Inventory API/UI permission'),
    ('Pricing.SellerVariantPrice.Update', 'Update seller variant price', 'Pricing.SellerVariantPrice', 4, 3, 'Inventory API/UI permission'),

    ('Category.Read', 'Legacy category read', 'Legacy.Category', 4, 3, 'Dashboard compatibility alias'),
    ('Category.Search', 'Legacy category search', 'Legacy.Category', 4, 3, 'Dashboard compatibility alias'),
    ('Category.Create', 'Legacy category create', 'Legacy.Category', 4, 3, 'Dashboard compatibility alias'),
    ('Category.Update', 'Legacy category update', 'Legacy.Category', 4, 3, 'Dashboard compatibility alias'),
    ('Category.Move', 'Legacy category move', 'Legacy.Category', 4, 3, 'Dashboard compatibility alias'),
    ('Category.Activate', 'Legacy category activate', 'Legacy.Category', 4, 3, 'Dashboard compatibility alias'),
    ('Category.Deactivate', 'Legacy category deactivate', 'Legacy.Category', 4, 3, 'Dashboard compatibility alias'),
    ('Category.Delete', 'Legacy category delete', 'Legacy.Category', 4, 3, 'Dashboard compatibility alias'),
    ('CategoryAttributeRule.Assign', 'Legacy category attribute rule assign', 'Legacy.CategoryAttributeRule', 4, 3, 'Dashboard compatibility alias'),
    ('CategoryAttributeRule.Create', 'Legacy category attribute rule create', 'Legacy.CategoryAttributeRule', 4, 3, 'Dashboard compatibility alias'),
    ('CategoryAttributeRule.Update', 'Legacy category attribute rule update', 'Legacy.CategoryAttributeRule', 4, 3, 'Dashboard compatibility alias'),
    ('CategoryAttributeRule.Activate', 'Legacy category attribute rule activate', 'Legacy.CategoryAttributeRule', 4, 3, 'Dashboard compatibility alias'),
    ('CategoryAttributeRule.Deactivate', 'Legacy category attribute rule deactivate', 'Legacy.CategoryAttributeRule', 4, 3, 'Dashboard compatibility alias'),
    ('CategoryAttributeRule.Remove', 'Legacy category attribute rule remove', 'Legacy.CategoryAttributeRule', 4, 3, 'Dashboard compatibility alias'),
    ('CategoryAttributeRule.Delete', 'Legacy category attribute rule delete', 'Legacy.CategoryAttributeRule', 4, 3, 'Dashboard compatibility alias'),
    ('Product.Read', 'Legacy product read', 'Legacy.Product', 4, 3, 'Dashboard compatibility alias'),
    ('Product.Search', 'Legacy product search', 'Legacy.Product', 4, 3, 'Dashboard compatibility alias'),
    ('Product.Create', 'Legacy product create', 'Legacy.Product', 4, 3, 'Dashboard compatibility alias'),
    ('Product.Update', 'Legacy product update', 'Legacy.Product', 4, 3, 'Dashboard compatibility alias'),
    ('Product.Activate', 'Legacy product activate', 'Legacy.Product', 4, 3, 'Dashboard compatibility alias'),
    ('Product.Deactivate', 'Legacy product deactivate', 'Legacy.Product', 4, 3, 'Dashboard compatibility alias'),
    ('Product.Delete', 'Legacy product delete', 'Legacy.Product', 4, 3, 'Dashboard compatibility alias'),
    ('Product.ChangeCategory', 'Legacy product change category', 'Legacy.Product', 4, 3, 'Dashboard compatibility alias'),
    ('ProductVariant.Read', 'Legacy variant read', 'Legacy.ProductVariant', 4, 3, 'Dashboard compatibility alias'),
    ('ProductVariant.Search', 'Legacy variant search', 'Legacy.ProductVariant', 4, 3, 'Dashboard compatibility alias'),
    ('ProductVariant.Create', 'Legacy variant create', 'Legacy.ProductVariant', 4, 3, 'Dashboard compatibility alias'),
    ('ProductVariant.Update', 'Legacy variant update', 'Legacy.ProductVariant', 4, 3, 'Dashboard compatibility alias'),
    ('ProductVariant.Activate', 'Legacy variant activate', 'Legacy.ProductVariant', 4, 3, 'Dashboard compatibility alias'),
    ('ProductVariant.Deactivate', 'Legacy variant deactivate', 'Legacy.ProductVariant', 4, 3, 'Dashboard compatibility alias'),
    ('ProductVariant.Delete', 'Legacy variant delete', 'Legacy.ProductVariant', 4, 3, 'Dashboard compatibility alias'),
    ('ProductVariant.ChangeTrackingPolicy', 'Legacy variant change tracking policy', 'Legacy.ProductVariant', 4, 3, 'Dashboard compatibility alias'),
    ('ProductVariant.ChangeBaseUom', 'Legacy variant change base UOM', 'Legacy.ProductVariant', 4, 3, 'Dashboard compatibility alias'),
    ('ProductVariant.LockInventoryMovement', 'Legacy variant lock inventory movement', 'Legacy.ProductVariant', 4, 3, 'Dashboard compatibility alias'),
    ('AttributeDefinition.Create', 'Legacy attribute definition create', 'Legacy.AttributeDefinition', 4, 3, 'Dashboard compatibility alias'),
    ('AttributeDefinition.Update', 'Legacy attribute definition update', 'Legacy.AttributeDefinition', 4, 3, 'Dashboard compatibility alias'),
    ('AttributeDefinition.Activate', 'Legacy attribute definition activate', 'Legacy.AttributeDefinition', 4, 3, 'Dashboard compatibility alias'),
    ('AttributeDefinition.Deactivate', 'Legacy attribute definition deactivate', 'Legacy.AttributeDefinition', 4, 3, 'Dashboard compatibility alias'),
    ('AttributeDefinition.Delete', 'Legacy attribute definition delete', 'Legacy.AttributeDefinition', 4, 3, 'Dashboard compatibility alias'),
    ('AttributeOption.Create', 'Legacy attribute option create', 'Legacy.AttributeOption', 4, 3, 'Dashboard compatibility alias'),
    ('AttributeOption.Update', 'Legacy attribute option update', 'Legacy.AttributeOption', 4, 3, 'Dashboard compatibility alias'),
    ('AttributeOption.Activate', 'Legacy attribute option activate', 'Legacy.AttributeOption', 4, 3, 'Dashboard compatibility alias'),
    ('AttributeOption.Deactivate', 'Legacy attribute option deactivate', 'Legacy.AttributeOption', 4, 3, 'Dashboard compatibility alias'),
    ('AttributeOption.Delete', 'Legacy attribute option delete', 'Legacy.AttributeOption', 4, 3, 'Dashboard compatibility alias'),
    ('ProductAttributeValue.Set', 'Legacy product attribute value set', 'Legacy.ProductAttributeValue', 4, 3, 'Dashboard compatibility alias'),
    ('ProductAttributeValue.Remove', 'Legacy product attribute value remove', 'Legacy.ProductAttributeValue', 4, 3, 'Dashboard compatibility alias'),
    ('VariantAttributeValue.Set', 'Legacy variant attribute value set', 'Legacy.VariantAttributeValue', 4, 3, 'Dashboard compatibility alias'),
    ('VariantAttributeValue.Remove', 'Legacy variant attribute value remove', 'Legacy.VariantAttributeValue', 4, 3, 'Dashboard compatibility alias'),
    ('ProductVariantUomConversion.Upsert', 'Legacy variant UOM conversion upsert', 'Legacy.ProductVariantUomConversion', 4, 3, 'Dashboard compatibility alias'),
    ('ProductVariantUomConversion.Remove', 'Legacy variant UOM conversion remove', 'Legacy.ProductVariantUomConversion', 4, 3, 'Dashboard compatibility alias'),
    ('Warehouse.Read', 'Legacy warehouse read', 'Legacy.Warehouse', 4, 3, 'Dashboard compatibility alias'),
    ('Warehouse.Search', 'Legacy warehouse search', 'Legacy.Warehouse', 4, 3, 'Dashboard compatibility alias'),
    ('Warehouse.Create', 'Legacy warehouse create', 'Legacy.Warehouse', 4, 3, 'Dashboard compatibility alias'),
    ('Warehouse.Update', 'Legacy warehouse update', 'Legacy.Warehouse', 4, 3, 'Dashboard compatibility alias'),
    ('Warehouse.Delete', 'Legacy warehouse delete', 'Legacy.Warehouse', 4, 3, 'Dashboard compatibility alias'),
    ('Location.Create', 'Legacy location create', 'Legacy.Location', 4, 3, 'Dashboard compatibility alias'),
    ('Location.Update', 'Legacy location update', 'Legacy.Location', 4, 3, 'Dashboard compatibility alias'),
    ('Location.Delete', 'Legacy location delete', 'Legacy.Location', 4, 3, 'Dashboard compatibility alias'),
    ('InventoryDocument.Read', 'Legacy inventory document read', 'Legacy.InventoryDocument', 4, 3, 'Dashboard compatibility alias'),
    ('InventoryDocument.Search', 'Legacy inventory document search', 'Legacy.InventoryDocument', 4, 3, 'Dashboard compatibility alias'),
    ('InventoryDocument.Create', 'Legacy inventory document create', 'Legacy.InventoryDocument', 4, 3, 'Dashboard compatibility alias'),
    ('InventoryDocument.Approve', 'Legacy inventory document approve', 'Legacy.InventoryDocument', 4, 3, 'Dashboard compatibility alias'),
    ('InventoryDocument.Reject', 'Legacy inventory document reject', 'Legacy.InventoryDocument', 4, 3, 'Dashboard compatibility alias'),
    ('InventoryDocument.Cancel', 'Legacy inventory document cancel', 'Legacy.InventoryDocument', 4, 3, 'Dashboard compatibility alias'),
    ('InventoryDocument.Post', 'Legacy inventory document post', 'Legacy.InventoryDocument', 4, 3, 'Dashboard compatibility alias'),
    ('Document.Read', 'Legacy document read', 'Legacy.Document', 4, 3, 'Dashboard compatibility alias'),
    ('Document.Create', 'Legacy document create', 'Legacy.Document', 4, 3, 'Dashboard compatibility alias'),
    ('Document.Approve', 'Legacy document approve', 'Legacy.Document', 4, 3, 'Dashboard compatibility alias'),
    ('Document.Reject', 'Legacy document reject', 'Legacy.Document', 4, 3, 'Dashboard compatibility alias'),
    ('Document.Cancel', 'Legacy document cancel', 'Legacy.Document', 4, 3, 'Dashboard compatibility alias'),
    ('Document.Post', 'Legacy document post', 'Legacy.Document', 4, 3, 'Dashboard compatibility alias')
),
normalized_seed AS (
    SELECT DISTINCT ON ("Code")
        "Code",
        "Title",
        "Module",
        "Type",
        "Scope",
        "Description"
    FROM permission_seed
    ORDER BY "Code"
)
INSERT INTO "Permissions"
(
    "BusinessKey",
    "Code",
    "Title",
    "Module",
    "Type",
    "Scope",
    "Description",
    "IsActive"
)
SELECT
    (
        substr(md5("Code"), 1, 8) || '-' ||
        substr(md5("Code"), 9, 4) || '-' ||
        substr(md5("Code"), 13, 4) || '-' ||
        substr(md5("Code"), 17, 4) || '-' ||
        substr(md5("Code"), 21, 12)
    )::uuid AS "BusinessKey",
    "Code",
    "Title",
    "Module",
    "Type",
    "Scope",
    "Description",
    true AS "IsActive"
FROM normalized_seed
ON CONFLICT ("Code") DO UPDATE
SET
    "Title" = EXCLUDED."Title",
    "Module" = EXCLUDED."Module",
    "Type" = EXCLUDED."Type",
    "Scope" = EXCLUDED."Scope",
    "Description" = EXCLUDED."Description",
    "IsActive" = true;
