CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserBusinessKey" uuid NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    CREATE TABLE "Memberships" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" text NOT NULL,
        "UserBusinessKey" uuid NOT NULL,
        "OrganizationBusinessKey" uuid NOT NULL,
        "StartDateTime" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_Memberships" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    CREATE TABLE "Organizations" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" text NOT NULL,
        "Name" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_Organizations" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    CREATE TABLE "Permissions" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Code" text NOT NULL,
        "Scope" smallint NOT NULL,
        "Description" text,
        "IsActive" boolean NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_Permissions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    CREATE TABLE "RefreshTokens" (
        "Token" character varying(500) NOT NULL,
        "UserId" bigint NOT NULL,
        "ExpirationDate" timestamp with time zone NOT NULL,
        "IsRevoked" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ReplacedByToken" character varying(500),
        "ReasonRevoked" character varying(500),
        CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Token")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    CREATE TABLE "Roles" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" text NOT NULL,
        "BusinessKey" uuid NOT NULL,
        "Scope" smallint NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    CREATE TABLE "UserRoleAssignments" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RoleBusinessKey" uuid NOT NULL,
        "MembershipBusinessKey" uuid NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_UserRoleAssignments" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    CREATE TABLE "Users" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "MobileNumber" text,
        "Code" text,
        "FullName" text,
        "City" text,
        "Province" text,
        "MaxAllowedExpertiseAmount" numeric NOT NULL,
        "MaxAllowedDailyCaseReferral" numeric NOT NULL,
        "MaxAllowedOpenCases" numeric NOT NULL,
        "ProfileImageBase64" text,
        "ExpirationDate" timestamp with time zone,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" bigint NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" bigint NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" bigint NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" bigint NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" bigint NOT NULL,
        "RoleId" bigint NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    CREATE TABLE "RolePermissions" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RoleBusinessKey" uuid NOT NULL,
        "PermissionBusinessKey" uuid NOT NULL,
        "AppRoleId" bigint,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RolePermissions_Roles_AppRoleId" FOREIGN KEY ("AppRoleId") REFERENCES "Roles" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    CREATE INDEX "IX_RefreshTokens_ExpirationDate" ON "RefreshTokens" ("ExpirationDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    CREATE INDEX "IX_RolePermissions_AppRoleId" ON "RolePermissions" ("AppRoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    CREATE UNIQUE INDEX "IX_Roles_TenantId_NormalizedName" ON "Roles" ("TenantId", "NormalizedName") WHERE "NormalizedName" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304220412_init') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260304220412_init', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260305103240_email-nullable-in-user') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260305103240_email-nullable-in-user', '9.0.11');
    END IF;
END $EF$;
COMMIT;

