BEGIN;

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" varchar(150) NOT NULL,
    "ProductVersion" varchar(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE IF NOT EXISTS "AspNetUsers" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserBusinessKey" uuid NOT NULL,
    "UserName" varchar(256) NULL,
    "NormalizedUserName" varchar(256) NULL,
    "Email" varchar(256) NULL,
    "NormalizedEmail" varchar(256) NULL,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text NULL,
    "SecurityStamp" text NULL,
    "ConcurrencyStamp" text NULL,
    "PhoneNumber" text NULL,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamptz NULL,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Memberships" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" text NOT NULL,
    "UserBusinessKey" uuid NOT NULL,
    "OrganizationBusinessKey" uuid NOT NULL,
    "StartDateTime" timestamptz NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedByUserId" varchar(50) NULL,
    "CreatedDateTime" timestamptz NULL,
    "ModifiedByUserId" varchar(50) NULL,
    "ModifiedDateTime" timestamptz NULL,
    "BusinessKey" uuid NOT NULL,
    CONSTRAINT "PK_Memberships" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Organizations" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" text NOT NULL,
    "Name" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedByUserId" varchar(50) NULL,
    "CreatedDateTime" timestamptz NULL,
    "ModifiedByUserId" varchar(50) NULL,
    "ModifiedDateTime" timestamptz NULL,
    "BusinessKey" uuid NOT NULL,
    CONSTRAINT "PK_Organizations" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Permissions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Code" text NOT NULL,
    "Scope" smallint NOT NULL,
    "Description" text NULL,
    "IsActive" boolean NOT NULL,
    "CreatedByUserId" varchar(50) NULL,
    "CreatedDateTime" timestamptz NULL,
    "ModifiedByUserId" varchar(50) NULL,
    "ModifiedDateTime" timestamptz NULL,
    "BusinessKey" uuid NOT NULL,
    CONSTRAINT "PK_Permissions" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "RefreshTokens" (
    "Token" varchar(500) NOT NULL,
    "UserId" bigint NOT NULL,
    "ExpirationDate" timestamptz NOT NULL,
    "IsRevoked" boolean NOT NULL,
    "CreatedAt" timestamptz NOT NULL,
    "ReplacedByToken" varchar(500) NULL,
    "ReasonRevoked" varchar(500) NULL,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Token")
);

CREATE TABLE IF NOT EXISTS "Roles" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" text NOT NULL,
    "BusinessKey" uuid NOT NULL,
    "Scope" smallint NOT NULL,
    "Name" varchar(256) NULL,
    "NormalizedName" varchar(256) NULL,
    "ConcurrencyStamp" text NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "UserRoleAssignments" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RoleBusinessKey" uuid NOT NULL,
    "MembershipBusinessKey" uuid NOT NULL,
    "CreatedByUserId" varchar(50) NULL,
    "CreatedDateTime" timestamptz NULL,
    "ModifiedByUserId" varchar(50) NULL,
    "ModifiedDateTime" timestamptz NULL,
    "BusinessKey" uuid NOT NULL,
    CONSTRAINT "PK_UserRoleAssignments" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Users" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "MobileNumber" text NULL,
    "Code" text NULL,
    "FullName" text NULL,
    "City" text NULL,
    "Province" text NULL,
    "MaxAllowedExpertiseAmount" numeric NOT NULL,
    "MaxAllowedDailyCaseReferral" numeric NOT NULL,
    "MaxAllowedOpenCases" numeric NOT NULL,
    "ProfileImageBase64" text NULL,
    "ExpirationDate" timestamptz NULL,
    "CreatedByUserId" varchar(50) NULL,
    "CreatedDateTime" timestamptz NULL,
    "ModifiedByUserId" varchar(50) NULL,
    "ModifiedDateTime" timestamptz NULL,
    "BusinessKey" uuid NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "OtpCodes" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "MobileNumber" varchar(32) NOT NULL,
    "Code" varchar(16) NOT NULL,
    "CreatedAt" timestamptz NOT NULL,
    "ExpiresAt" timestamptz NOT NULL,
    "IsUsed" boolean NOT NULL,
    CONSTRAINT "PK_OtpCodes" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text NULL,
    "UserId" bigint NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserTokens" (
    "UserId" bigint NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text NULL,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" bigint NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserRoles" (
    "UserId" bigint NOT NULL,
    "RoleId" bigint NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "RolePermissions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RoleBusinessKey" uuid NOT NULL,
    "PermissionBusinessKey" uuid NOT NULL,
    "AppRoleId" bigint NULL,
    "CreatedByUserId" varchar(50) NULL,
    "CreatedDateTime" timestamptz NULL,
    "ModifiedByUserId" varchar(50) NULL,
    "ModifiedDateTime" timestamptz NULL,
    "BusinessKey" uuid NOT NULL,
    CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RolePermissions_Roles_AppRoleId" FOREIGN KEY ("AppRoleId") REFERENCES "Roles" ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
CREATE INDEX IF NOT EXISTS "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
CREATE INDEX IF NOT EXISTS "IX_RefreshTokens_ExpirationDate" ON "RefreshTokens" ("ExpirationDate");
CREATE INDEX IF NOT EXISTS "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_RolePermissions_AppRoleId" ON "RolePermissions" ("AppRoleId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Roles_TenantId_NormalizedName" ON "Roles" ("TenantId", "NormalizedName") WHERE "NormalizedName" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "IX_OtpCodes_MobileNumber" ON "OtpCodes" ("MobileNumber");
CREATE INDEX IF NOT EXISTS "IX_OtpCodes_CreatedAt" ON "OtpCodes" ("CreatedAt");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES
    ('20260304220412_init', '9.0.11'),
    ('20260305103240_email-nullable-in-user', '9.0.11')
ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;
