START TRANSACTION;

CREATE TABLE "Tags" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TagName" character varying(256) NOT NULL,
    "TagColor" character varying(64),
    "CreatedByUserId" character varying(50),
    "CreatedDateTime" timestamp with time zone,
    "ModifiedByUserId" character varying(50),
    "ModifiedDateTime" timestamp with time zone,
    "OrganizationBusinessKey" character varying(50),
    "TenantId" character varying(100),
    "BusinessKey" uuid NOT NULL,
    CONSTRAINT "PK_Tags" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Tags_BusinessKey" ON "Tags" ("BusinessKey");

CREATE UNIQUE INDEX "IX_Tags_TagName" ON "Tags" ("TagName");

CREATE INDEX "IX_Tags_OrganizationBusinessKey" ON "Tags" ("OrganizationBusinessKey");

CREATE INDEX "IX_Tags_TenantId" ON "Tags" ("TenantId");

ALTER TABLE "VariantTags" ADD COLUMN "TagRef" uuid;

INSERT INTO "Tags" (
    "TagName",
    "TagColor",
    "CreatedByUserId",
    "CreatedDateTime",
    "ModifiedByUserId",
    "ModifiedDateTime",
    "OrganizationBusinessKey",
    "TenantId",
    "BusinessKey"
)
SELECT DISTINCT ON (vt."TagName")
    vt."TagName",
    vt."TagColor",
    NULL,
    NULL,
    NULL,
    NULL,
    vt."OrganizationBusinessKey",
    vt."TenantId",
    (
        substr(vt.row_hash, 1, 8) || '-' ||
        substr(vt.row_hash, 9, 4) || '-' ||
        substr(vt.row_hash, 13, 4) || '-' ||
        substr(vt.row_hash, 17, 4) || '-' ||
        substr(vt.row_hash, 21, 12)
    )::uuid
FROM (
    SELECT
        vt.*,
        md5(random()::text || clock_timestamp()::text) AS row_hash
    FROM "VariantTags" vt
) vt
ORDER BY vt."TagName", (vt."TagColor" IS NULL), vt."DisplayOrder", vt."Id";

UPDATE "VariantTags" vt
SET "TagRef" = t."BusinessKey"
FROM "Tags" t
WHERE vt."TagName" = t."TagName";

ALTER TABLE "VariantTags" ALTER COLUMN "TagRef" SET NOT NULL;

ALTER TABLE "VariantTags"
    ADD CONSTRAINT "FK_VariantTags_Tags_TagRef"
    FOREIGN KEY ("TagRef") REFERENCES "Tags" ("BusinessKey") ON DELETE CASCADE;

CREATE INDEX "IX_VariantTags_TagRef" ON "VariantTags" ("TagRef");

CREATE UNIQUE INDEX "IX_VariantTags_VariantRef_TagRef" ON "VariantTags" ("VariantRef", "TagRef");

DROP INDEX "IX_VariantTags_VariantRef_TagName";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260520144543_AddTagsMasterAndVariantTagRef', '9.0.11');

COMMIT;
