START TRANSACTION;
CREATE TABLE "VariantTags" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "VariantRef" uuid NOT NULL,
    "TagName" character varying(256) NOT NULL,
    "TagColor" character varying(64),
    "DisplayOrder" integer NOT NULL,
    "CreatedByUserId" character varying(50),
    "CreatedDateTime" timestamp with time zone,
    "ModifiedByUserId" character varying(50),
    "ModifiedDateTime" timestamp with time zone,
    "OrganizationBusinessKey" character varying(50),
    "ProductVariantId" bigint,
    "TenantId" character varying(100),
    "BusinessKey" uuid NOT NULL,
    CONSTRAINT "PK_VariantTags" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VariantTags_ProductVariants_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES "ProductVariants" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_VariantTags_OrganizationBusinessKey" ON "VariantTags" ("OrganizationBusinessKey");

CREATE INDEX "IX_VariantTags_ProductVariantId" ON "VariantTags" ("ProductVariantId");

CREATE INDEX "IX_VariantTags_TenantId" ON "VariantTags" ("TenantId");

CREATE UNIQUE INDEX "IX_VariantTags_VariantRef_TagName" ON "VariantTags" ("VariantRef", "TagName");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260518150922_AddVariantTags', '9.0.11');

COMMIT;

