CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'SkyPearlFx') THEN
            CREATE SCHEMA "SkyPearlFx";
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "AttributeDefinitions" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Code" text NOT NULL,
        "Name" text NOT NULL,
        "DataType" integer NOT NULL,
        "Scope" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_AttributeDefinitions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "Categories" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ParentCategoryRef" uuid,
        "Code" text NOT NULL,
        "Name" text NOT NULL,
        "ImageFileKey" character varying(256),
        "ImageUrl" character varying(1024),
        "ImageThumbnailUrl" character varying(1024),
        "IsActive" boolean NOT NULL,
        "DisplayOrder" integer NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_Categories" PRIMARY KEY ("Id"),
        CONSTRAINT "AK_Categories_BusinessKey" UNIQUE ("BusinessKey")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "CategoryVariantNameFormulas" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CategoryRef" uuid NOT NULL,
        "Name" character varying(160) NOT NULL,
        "Separator" character varying(16) NOT NULL,
        "DisplayOrder" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_CategoryVariantNameFormulas" PRIMARY KEY ("Id"),
        CONSTRAINT "AK_CategoryVariantNameFormulas_BusinessKey" UNIQUE ("BusinessKey")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "Fulfillments" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "OrderRef" uuid NOT NULL,
        "SellerRef" uuid NOT NULL,
        "WarehouseRef" uuid NOT NULL,
        "ChannelRef" uuid NOT NULL,
        "Status" integer NOT NULL,
        "PickedAt" timestamp with time zone,
        "PackedAt" timestamp with time zone,
        "ShippedAt" timestamp with time zone,
        "ReturnedAt" timestamp with time zone,
        "CancelledAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_Fulfillments" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "InventoryDocuments" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "DocumentNo" text NOT NULL,
        "DocumentType" integer NOT NULL,
        "Status" integer NOT NULL,
        "ReferenceType" text,
        "ReferenceBusinessId" uuid,
        "WarehouseRef" uuid NOT NULL,
        "SellerRef" uuid NOT NULL,
        "OccurredAt" timestamp with time zone NOT NULL,
        "ApprovedAt" timestamp with time zone,
        "ApprovedBy" text,
        "PostedAt" timestamp with time zone,
        "PostedBy" text,
        "PostedTransactionRef" uuid,
        "CancelledAt" timestamp with time zone,
        "RejectedAt" timestamp with time zone,
        "CorrelationId" text,
        "IdempotencyKey" text,
        "ReasonCode" text,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_InventoryDocuments" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "InventoryReservations" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "OrderRef" uuid NOT NULL,
        "OrderItemRef" uuid NOT NULL,
        "VariantRef" uuid NOT NULL,
        "SellerRef" uuid NOT NULL,
        "WarehouseRef" uuid NOT NULL,
        "ChannelRef" uuid NOT NULL,
        "RequestedQuantity" numeric NOT NULL,
        "AllocatedQuantity" numeric NOT NULL,
        "ConsumedQuantity" numeric NOT NULL,
        "ReleasedQuantity" numeric NOT NULL,
        "Status" integer NOT NULL,
        "ExpiresAt" timestamp with time zone,
        "ConfirmedAt" timestamp with time zone,
        "ConsumedAt" timestamp with time zone,
        "ReleasedAt" timestamp with time zone,
        "RejectedAt" timestamp with time zone,
        "CorrelationId" text,
        "IdempotencyKey" text,
        "ReasonCode" text,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_InventoryReservations" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "InventorySourceBalances" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "SourceType" integer NOT NULL,
        "SourceDocumentRef" uuid,
        "SourceDocumentLineRef" uuid,
        "SourceTransactionRef" uuid,
        "SourceTransactionLineRef" uuid,
        "VariantRef" uuid NOT NULL,
        "SellerRef" uuid NOT NULL,
        "WarehouseRef" uuid NOT NULL,
        "LocationRef" uuid NOT NULL,
        "QualityStatusRef" uuid NOT NULL,
        "LotBatchNo" text,
        "SerialRef" uuid,
        "ReceivedQty" numeric NOT NULL,
        "AllocatedQty" numeric NOT NULL,
        "ConsumedQty" numeric NOT NULL,
        "AvailableQty" numeric NOT NULL,
        "RemainingQty" numeric NOT NULL,
        "BaseUomRef" uuid NOT NULL,
        "Status" integer NOT NULL,
        "OpenedAt" timestamp with time zone NOT NULL,
        "ClosedAt" timestamp with time zone,
        "LastConsumedAt" timestamp with time zone,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_InventorySourceBalances" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "InventoryTransactions" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TransactionNo" text NOT NULL,
        "TransactionType" integer NOT NULL,
        "ReferenceType" text,
        "ReferenceBusinessId" uuid,
        "WarehouseRef" uuid NOT NULL,
        "SellerRef" uuid NOT NULL,
        "OccurredAt" timestamp with time zone NOT NULL,
        "PostedAt" timestamp with time zone,
        "Status" integer NOT NULL,
        "CorrelationId" text,
        "IdempotencyKey" text,
        "ReasonCode" text,
        "ReversedTransactionRef" uuid,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_InventoryTransactions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "Locations" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "WarehouseRef" uuid NOT NULL,
        "Aisle" text,
        "Rack" text,
        "Shelf" text,
        "Bin" text,
        "LocationCode" text NOT NULL,
        "LocationType" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_Locations" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "SkyPearlFx"."OutboxEvents" (
        "OutBoxEventItemId" bigint GENERATED BY DEFAULT AS IDENTITY,
        "EventId" uuid NOT NULL,
        "AccuredByUserId" character varying(255),
        "AccuredOn" timestamp with time zone NOT NULL,
        "AggregateName" character varying(255),
        "AggregateTypeName" character varying(500),
        "AggregateId" text,
        "EventName" character varying(255),
        "EventTypeName" character varying(500),
        "EventPayload" text,
        "TraceId" character varying(100),
        "SpanId" character varying(100),
        "IsProcessed" boolean NOT NULL,
        CONSTRAINT "PK_OutboxEvents" PRIMARY KEY ("OutBoxEventItemId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "PriceChannels" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Code" text NOT NULL,
        "Name" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_PriceChannels" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "PriceTypes" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Code" text NOT NULL,
        "Name" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_PriceTypes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "Products" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CategoryRef" uuid NOT NULL,
        "CategorySchemaVersionRef" uuid NOT NULL,
        "BaseSku" text NOT NULL,
        "Name" text NOT NULL,
        "DefaultUomRef" uuid NOT NULL,
        "TaxCategoryRef" uuid,
        "ImageFileKey" character varying(256),
        "ImageUrl" character varying(1024),
        "ImageThumbnailUrl" character varying(1024),
        "IsActive" boolean NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "ProductVariants" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ProductRef" uuid NOT NULL,
        "VariantSku" text NOT NULL,
        "Barcode" text,
        "TrackingPolicy" integer NOT NULL,
        "BaseUomRef" uuid NOT NULL,
        "IsActive" boolean NOT NULL,
        "InventoryMovementLocked" boolean NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_ProductVariants" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "QualityStatuses" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Code" text NOT NULL,
        "Name" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_QualityStatuses" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "ReturnRequests" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "OrderRef" uuid NOT NULL,
        "OrderItemRef" uuid NOT NULL,
        "SellerRef" uuid NOT NULL,
        "WarehouseRef" uuid NOT NULL,
        "Status" integer NOT NULL,
        "ReasonCode" text,
        "RequestedAt" timestamp with time zone NOT NULL,
        "ApprovedAt" timestamp with time zone,
        "RejectedAt" timestamp with time zone,
        "ReceivedAt" timestamp with time zone,
        "ClosedAt" timestamp with time zone,
        "ApprovedBy" text,
        "RejectedBy" text,
        "ReceivedBy" text,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_ReturnRequests" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "Sellers" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Code" text NOT NULL,
        "Name" text NOT NULL,
        "IsSystemOwner" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_Sellers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "SellerVariantPrices" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "SellerRef" uuid NOT NULL,
        "VariantRef" uuid NOT NULL,
        "PriceTypeRef" uuid NOT NULL,
        "PriceChannelRef" uuid NOT NULL,
        "Amount" numeric NOT NULL,
        "Currency" text NOT NULL,
        "MinQty" numeric NOT NULL,
        "Priority" integer NOT NULL,
        "EffectiveFrom" timestamp with time zone,
        "EffectiveTo" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_SellerVariantPrices" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "SerialItems" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "SerialNo" character varying(128) NOT NULL,
        "VariantRef" uuid NOT NULL,
        "SellerRef" uuid NOT NULL,
        "WarehouseRef" uuid NOT NULL,
        "LocationRef" uuid NOT NULL,
        "StockDetailRef" uuid,
        "QualityStatusRef" uuid NOT NULL,
        "LotBatchNo" character varying(128),
        "Status" integer NOT NULL,
        "DateScannedIn" timestamp with time zone NOT NULL,
        "LastTransactionRef" uuid,
        "LastUpdatedAt" timestamp with time zone NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_SerialItems" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "StockDetails" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "VariantRef" uuid NOT NULL,
        "SellerRef" uuid NOT NULL,
        "WarehouseRef" uuid NOT NULL,
        "LocationRef" uuid NOT NULL,
        "QualityStatusRef" uuid NOT NULL,
        "LotBatchNo" text,
        "QuantityOnHand" numeric NOT NULL,
        "FirstReceivedAt" timestamp with time zone NOT NULL,
        "LastReceivedAt" timestamp with time zone NOT NULL,
        "LastIssuedAt" timestamp with time zone,
        "LastUpdatedAt" timestamp with time zone NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_StockDetails" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "UnitOfMeasures" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Code" text NOT NULL,
        "Name" text NOT NULL,
        "Precision" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_UnitOfMeasures" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "Warehouses" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Code" text NOT NULL,
        "Name" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_Warehouses" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "AttributeOptions" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "AttributeRef" uuid NOT NULL,
        "Name" text NOT NULL,
        "Value" text NOT NULL,
        "DisplayOrder" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "AttributeDefinitionId" bigint,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_AttributeOptions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AttributeOptions_AttributeDefinitions_AttributeDefinitionId" FOREIGN KEY ("AttributeDefinitionId") REFERENCES "AttributeDefinitions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "CategorySchemaVersions" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CategoryRef" uuid NOT NULL,
        "VersionNo" integer NOT NULL,
        "IsCurrent" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ChangeSummary" text,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_CategorySchemaVersions" PRIMARY KEY ("Id"),
        CONSTRAINT "AK_CategorySchemaVersions_BusinessKey" UNIQUE ("BusinessKey"),
        CONSTRAINT "FK_CategorySchemaVersions_Categories_CategoryRef" FOREIGN KEY ("CategoryRef") REFERENCES "Categories" ("BusinessKey") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "CategoryVariantNameFormulaParts" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "FormulaRef" uuid NOT NULL,
        "AttributeRef" uuid NOT NULL,
        "SortOrder" integer NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_CategoryVariantNameFormulaParts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CategoryVariantNameFormulaParts_CategoryVariantNameFormulas~" FOREIGN KEY ("FormulaRef") REFERENCES "CategoryVariantNameFormulas" ("BusinessKey") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "FulfillmentLines" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "FulfillmentRef" uuid NOT NULL,
        "VariantRef" uuid NOT NULL,
        "Qty" numeric NOT NULL,
        "UomRef" uuid NOT NULL,
        "BaseQty" numeric NOT NULL,
        "BaseUomRef" uuid NOT NULL,
        "SourceLocationRef" uuid,
        "LotBatchNo" text,
        "ReservationAllocationRef" uuid,
        "Status" integer NOT NULL,
        "PickedQty" numeric NOT NULL,
        "PackedQty" numeric NOT NULL,
        "ShippedQty" numeric NOT NULL,
        "ReturnedQty" numeric NOT NULL,
        "PickedAt" timestamp with time zone,
        "PackedAt" timestamp with time zone,
        "ShippedAt" timestamp with time zone,
        "ReturnedAt" timestamp with time zone,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "FulfillmentId" bigint,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_FulfillmentLines" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FulfillmentLines_Fulfillments_FulfillmentId" FOREIGN KEY ("FulfillmentId") REFERENCES "Fulfillments" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "FulfillmentTransitions" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "FulfillmentRef" uuid NOT NULL,
        "FromStatus" integer NOT NULL,
        "ToStatus" integer NOT NULL,
        "ReasonCode" text,
        "ChangedAt" timestamp with time zone NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "FulfillmentId" bigint,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_FulfillmentTransitions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FulfillmentTransitions_Fulfillments_FulfillmentId" FOREIGN KEY ("FulfillmentId") REFERENCES "Fulfillments" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "InventoryDocumentLines" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "VariantRef" uuid NOT NULL,
        "Qty" numeric NOT NULL,
        "UomRef" uuid NOT NULL,
        "BaseQty" numeric NOT NULL,
        "BaseUomRef" uuid NOT NULL,
        "SourceLocationRef" uuid,
        "DestinationLocationRef" uuid,
        "QualityStatusRef" uuid,
        "FromQualityStatusRef" uuid,
        "ToQualityStatusRef" uuid,
        "LotBatchNo" text,
        "ReasonCode" text,
        "AdjustmentDirection" integer,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "InventoryDocumentId" bigint,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_InventoryDocumentLines" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_InventoryDocumentLines_InventoryDocuments_InventoryDocument~" FOREIGN KEY ("InventoryDocumentId") REFERENCES "InventoryDocuments" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "ReservationAllocations" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ReservationRef" uuid NOT NULL,
        "StockDetailRef" uuid,
        "VariantRef" uuid NOT NULL,
        "WarehouseRef" uuid NOT NULL,
        "LocationRef" uuid NOT NULL,
        "QualityStatusRef" uuid NOT NULL,
        "LotBatchNo" text,
        "SerialRef" uuid,
        "AllocatedQty" numeric NOT NULL,
        "AllocatedAt" timestamp with time zone NOT NULL,
        "ReleasedQty" numeric NOT NULL,
        "ConsumedQty" numeric NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "InventoryReservationId" bigint,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_ReservationAllocations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ReservationAllocations_InventoryReservations_InventoryReser~" FOREIGN KEY ("InventoryReservationId") REFERENCES "InventoryReservations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "ReservationTransitions" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ReservationRef" uuid NOT NULL,
        "FromStatus" integer NOT NULL,
        "ToStatus" integer NOT NULL,
        "ReasonCode" text,
        "ChangedAt" timestamp with time zone NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "InventoryReservationId" bigint,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_ReservationTransitions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ReservationTransitions_InventoryReservations_InventoryReser~" FOREIGN KEY ("InventoryReservationId") REFERENCES "InventoryReservations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "InventorySourceAllocations" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "SourceBalanceRef" uuid NOT NULL,
        "ReservationRef" uuid NOT NULL,
        "ReservationAllocationRef" uuid,
        "VariantRef" uuid NOT NULL,
        "AllocatedQty" numeric NOT NULL,
        "BaseUomRef" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ReleasedQty" numeric NOT NULL,
        "ConsumedQty" numeric NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "InventorySourceBalanceId" bigint,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_InventorySourceAllocations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_InventorySourceAllocations_InventorySourceBalances_Inventor~" FOREIGN KEY ("InventorySourceBalanceId") REFERENCES "InventorySourceBalances" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "InventorySourceConsumptions" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "OutboundTransactionRef" uuid NOT NULL,
        "OutboundTransactionLineRef" uuid,
        "SourceBalanceRef" uuid NOT NULL,
        "SourceDocumentRef" uuid,
        "SourceDocumentLineRef" uuid,
        "SourceTransactionRef" uuid,
        "SourceTransactionLineRef" uuid,
        "VariantRef" uuid NOT NULL,
        "SellerRef" uuid NOT NULL,
        "WarehouseRef" uuid NOT NULL,
        "LocationRef" uuid NOT NULL,
        "QualityStatusRef" uuid NOT NULL,
        "LotBatchNo" text,
        "SerialRef" uuid,
        "ConsumedQty" numeric NOT NULL,
        "BaseUomRef" uuid NOT NULL,
        "ReservationRef" uuid,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ReasonCode" text,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "InventorySourceBalanceId" bigint,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_InventorySourceConsumptions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_InventorySourceConsumptions_InventorySourceBalances_Invento~" FOREIGN KEY ("InventorySourceBalanceId") REFERENCES "InventorySourceBalances" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "InventoryTransactionLines" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "StockDetailRef" uuid,
        "VariantRef" uuid NOT NULL,
        "InputQty" numeric NOT NULL,
        "InputUomRef" uuid NOT NULL,
        "BaseQtyDelta" numeric NOT NULL,
        "BaseUomRef" uuid NOT NULL,
        "SourceLocationRef" uuid,
        "DestinationLocationRef" uuid,
        "OldQualityStatusRef" uuid,
        "NewQualityStatusRef" uuid,
        "LotBatchNo" text,
        "SerialRef" uuid,
        "ReasonCode" text,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "InventoryTransactionId" bigint,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_InventoryTransactionLines" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_InventoryTransactionLines_InventoryTransactions_InventoryTr~" FOREIGN KEY ("InventoryTransactionId") REFERENCES "InventoryTransactions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "ProductAttributeValues" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ProductRef" uuid NOT NULL,
        "AttributeRef" uuid NOT NULL,
        "Value" text,
        "OptionRef" uuid,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "ProductId" bigint,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_ProductAttributeValues" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProductAttributeValues_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "VariantAddOns" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "VariantRef" uuid NOT NULL,
        "AddOnVariantRef" uuid NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "ProductVariantId" bigint,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_VariantAddOns" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VariantAddOns_ProductVariants_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES "ProductVariants" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "VariantAttributeValues" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "VariantRef" uuid NOT NULL,
        "AttributeRef" uuid NOT NULL,
        "Value" text,
        "OptionRef" uuid,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "ProductVariantId" bigint,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_VariantAttributeValues" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VariantAttributeValues_ProductVariants_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES "ProductVariants" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "VariantComponents" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "VariantRef" uuid NOT NULL,
        "ComponentVariantRef" uuid NOT NULL,
        "WarehouseRef" uuid NOT NULL,
        "LocationRef" uuid NOT NULL,
        "Quantity" numeric NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "ProductVariantId" bigint,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_VariantComponents" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VariantComponents_ProductVariants_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES "ProductVariants" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "VariantImages" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "VariantRef" uuid NOT NULL,
        "FileKey" character varying(256) NOT NULL,
        "OriginalFileName" character varying(260) NOT NULL,
        "ContentType" character varying(128) NOT NULL,
        "OriginalUrl" character varying(1024) NOT NULL,
        "ThumbnailUrl" character varying(1024) NOT NULL,
        "DisplayOrder" integer NOT NULL,
        "IsPrimary" boolean NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "ProductVariantId" bigint,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_VariantImages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VariantImages_ProductVariants_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES "ProductVariants" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "VariantUomConversions" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "VariantRef" uuid NOT NULL,
        "FromUomRef" uuid NOT NULL,
        "ToUomRef" uuid NOT NULL,
        "Factor" numeric NOT NULL,
        "RoundingMode" integer NOT NULL,
        "IsBasePath" boolean NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "ProductVariantId" bigint,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_VariantUomConversions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VariantUomConversions_ProductVariants_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES "ProductVariants" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "ReturnLines" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ReturnRef" uuid NOT NULL,
        "VariantRef" uuid NOT NULL,
        "Qty" numeric NOT NULL,
        "UomRef" uuid NOT NULL,
        "BaseQty" numeric NOT NULL,
        "BaseUomRef" uuid NOT NULL,
        "LotBatchNo" text,
        "ExpectedCondition" text,
        "ReceivedCondition" text,
        "Disposition" integer NOT NULL,
        "ReceivedQty" numeric NOT NULL,
        "Status" integer NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "ReturnRequestId" bigint,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_ReturnLines" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ReturnLines_ReturnRequests_ReturnRequestId" FOREIGN KEY ("ReturnRequestId") REFERENCES "ReturnRequests" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "ReturnRequestTransitions" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ReturnRequestRef" uuid NOT NULL,
        "FromStatus" integer NOT NULL,
        "ToStatus" integer NOT NULL,
        "ReasonCode" text,
        "ChangedAt" timestamp with time zone NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "ReturnRequestId" bigint,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_ReturnRequestTransitions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ReturnRequestTransitions_ReturnRequests_ReturnRequestId" FOREIGN KEY ("ReturnRequestId") REFERENCES "ReturnRequests" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "Offers" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "PriceRef" uuid NOT NULL,
        "Name" text NOT NULL,
        "DiscountAmount" numeric,
        "DiscountPercent" numeric,
        "MaxQuantity" numeric,
        "Priority" integer NOT NULL,
        "StartAt" timestamp with time zone,
        "EndAt" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "SellerVariantPriceId" bigint,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_Offers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Offers_SellerVariantPrices_SellerVariantPriceId" FOREIGN KEY ("SellerVariantPriceId") REFERENCES "SellerVariantPrices" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "CategoryAttributeRules" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CategorySchemaVersionRef" uuid NOT NULL,
        "AttributeRef" uuid NOT NULL,
        "IsRequired" boolean NOT NULL,
        "IsVariant" boolean NOT NULL,
        "IsVariantCodeCovered" boolean NOT NULL,
        "DisplayOrder" integer NOT NULL,
        "IsOverridden" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_CategoryAttributeRules" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CategoryAttributeRules_CategorySchemaVersions_CategorySchem~" FOREIGN KEY ("CategorySchemaVersionRef") REFERENCES "CategorySchemaVersions" ("BusinessKey") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "FulfillmentLineSerials" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "FulfillmentLineRef" uuid NOT NULL,
        "SerialRef" uuid,
        "SerialNo" text NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "FulfillmentLineId" bigint,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_FulfillmentLineSerials" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FulfillmentLineSerials_FulfillmentLines_FulfillmentLineId" FOREIGN KEY ("FulfillmentLineId") REFERENCES "FulfillmentLines" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "InventoryDocumentLineSerials" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "DocumentLineRef" uuid NOT NULL,
        "SerialRef" uuid,
        "SerialNo" text NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "InventoryDocumentLineId" bigint,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_InventoryDocumentLineSerials" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_InventoryDocumentLineSerials_InventoryDocumentLines_Invento~" FOREIGN KEY ("InventoryDocumentLineId") REFERENCES "InventoryDocumentLines" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE TABLE "ReturnLineSerials" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ReturnLineRef" uuid NOT NULL,
        "SerialRef" uuid,
        "SerialNo" text NOT NULL,
        "CreatedByUserId" character varying(50),
        "CreatedDateTime" timestamp with time zone,
        "ModifiedByUserId" character varying(50),
        "ModifiedDateTime" timestamp with time zone,
        "ReturnLineId" bigint,
        "BusinessKey" uuid NOT NULL,
        CONSTRAINT "PK_ReturnLineSerials" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ReturnLineSerials_ReturnLines_ReturnLineId" FOREIGN KEY ("ReturnLineId") REFERENCES "ReturnLines" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_AttributeDefinitions_Code" ON "AttributeDefinitions" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_AttributeOptions_AttributeDefinitionId" ON "AttributeOptions" ("AttributeDefinitionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_AttributeOptions_AttributeRef_Name" ON "AttributeOptions" ("AttributeRef", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_AttributeOptions_AttributeRef_Value" ON "AttributeOptions" ("AttributeRef", "Value");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_Categories_Code" ON "Categories" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_CategoryAttributeRules_CategorySchemaVersionRef" ON "CategoryAttributeRules" ("CategorySchemaVersionRef");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_CategoryAttributeRules_CategorySchemaVersionRef_AttributeRef" ON "CategoryAttributeRules" ("CategorySchemaVersionRef", "AttributeRef");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_CategorySchemaVersions_CategoryRef_IsCurrent" ON "CategorySchemaVersions" ("CategoryRef", "IsCurrent");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_CategorySchemaVersions_CategoryRef_VersionNo" ON "CategorySchemaVersions" ("CategoryRef", "VersionNo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_CategoryVariantNameFormulaParts_FormulaRef_AttributeRef" ON "CategoryVariantNameFormulaParts" ("FormulaRef", "AttributeRef");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_CategoryVariantNameFormulaParts_FormulaRef_SortOrder" ON "CategoryVariantNameFormulaParts" ("FormulaRef", "SortOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_CategoryVariantNameFormulas_CategoryRef_Name" ON "CategoryVariantNameFormulas" ("CategoryRef", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_FulfillmentLines_FulfillmentId" ON "FulfillmentLines" ("FulfillmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_FulfillmentLineSerials_FulfillmentLineId" ON "FulfillmentLineSerials" ("FulfillmentLineId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_FulfillmentTransitions_FulfillmentId" ON "FulfillmentTransitions" ("FulfillmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_InventoryDocumentLines_InventoryDocumentId" ON "InventoryDocumentLines" ("InventoryDocumentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_InventoryDocumentLineSerials_InventoryDocumentLineId" ON "InventoryDocumentLineSerials" ("InventoryDocumentLineId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_InventoryDocuments_DocumentNo" ON "InventoryDocuments" ("DocumentNo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_InventorySourceAllocations_InventorySourceBalanceId" ON "InventorySourceAllocations" ("InventorySourceBalanceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_InventorySourceConsumptions_InventorySourceBalanceId" ON "InventorySourceConsumptions" ("InventorySourceBalanceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_InventoryTransactionLines_InventoryTransactionId" ON "InventoryTransactionLines" ("InventoryTransactionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_InventoryTransactions_TransactionNo" ON "InventoryTransactions" ("TransactionNo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_Locations_LocationCode" ON "Locations" ("LocationCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_Offers_PriceRef" ON "Offers" ("PriceRef");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_Offers_SellerVariantPriceId" ON "Offers" ("SellerVariantPriceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_PriceChannels_Code" ON "PriceChannels" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_PriceTypes_Code" ON "PriceTypes" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_ProductAttributeValues_ProductId" ON "ProductAttributeValues" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_ProductAttributeValues_ProductRef_AttributeRef" ON "ProductAttributeValues" ("ProductRef", "AttributeRef");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_Products_BaseSku" ON "Products" ("BaseSku");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_Products_CategoryRef" ON "Products" ("CategoryRef");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_Products_CategorySchemaVersionRef" ON "Products" ("CategorySchemaVersionRef");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_ProductVariants_Barcode" ON "ProductVariants" ("Barcode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_ProductVariants_VariantSku" ON "ProductVariants" ("VariantSku");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_QualityStatuses_Code" ON "QualityStatuses" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_ReservationAllocations_InventoryReservationId" ON "ReservationAllocations" ("InventoryReservationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_ReservationTransitions_InventoryReservationId" ON "ReservationTransitions" ("InventoryReservationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_ReturnLines_ReturnRequestId" ON "ReturnLines" ("ReturnRequestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_ReturnLineSerials_ReturnLineId" ON "ReturnLineSerials" ("ReturnLineId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_ReturnRequestTransitions_ReturnRequestId" ON "ReturnRequestTransitions" ("ReturnRequestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_Sellers_Code" ON "Sellers" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_SellerVariantPrices_SellerRef" ON "SellerVariantPrices" ("SellerRef");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_SellerVariantPrices_SellerRef_VariantRef_PriceTypeRef_Price~" ON "SellerVariantPrices" ("SellerRef", "VariantRef", "PriceTypeRef", "PriceChannelRef");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_SellerVariantPrices_VariantRef" ON "SellerVariantPrices" ("VariantRef");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_SerialItems_BusinessKey" ON "SerialItems" ("BusinessKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_SerialItems_SerialNo_VariantRef" ON "SerialItems" ("SerialNo", "VariantRef");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_StockDetails_VariantRef_SellerRef_WarehouseRef_LocationRef_~" ON "StockDetails" ("VariantRef", "SellerRef", "WarehouseRef", "LocationRef", "QualityStatusRef", "LotBatchNo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_UnitOfMeasures_Code" ON "UnitOfMeasures" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_VariantAddOns_ProductVariantId" ON "VariantAddOns" ("ProductVariantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_VariantAddOns_VariantRef_AddOnVariantRef" ON "VariantAddOns" ("VariantRef", "AddOnVariantRef");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_VariantAttributeValues_ProductVariantId" ON "VariantAttributeValues" ("ProductVariantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_VariantAttributeValues_VariantRef_AttributeRef" ON "VariantAttributeValues" ("VariantRef", "AttributeRef");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_VariantComponents_ProductVariantId" ON "VariantComponents" ("ProductVariantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_VariantComponents_VariantRef_ComponentVariantRef_WarehouseR~" ON "VariantComponents" ("VariantRef", "ComponentVariantRef", "WarehouseRef", "LocationRef");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_VariantImages_ProductVariantId" ON "VariantImages" ("ProductVariantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_VariantImages_VariantRef_FileKey" ON "VariantImages" ("VariantRef", "FileKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE INDEX "IX_VariantUomConversions_ProductVariantId" ON "VariantUomConversions" ("ProductVariantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_VariantUomConversions_VariantRef_FromUomRef_ToUomRef" ON "VariantUomConversions" ("VariantRef", "FromUomRef", "ToUomRef");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    CREATE UNIQUE INDEX "IX_Warehouses_Code" ON "Warehouses" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260512072808_InitialInventoryServiceSchema') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260512072808_InitialInventoryServiceSchema', '9.0.11');
    END IF;
END $EF$;
COMMIT;

