// <auto-generated />
using System;
using Insurance.Infra.Persistence.Sql.Commands;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Insurance.Infra.Persistence.Sql.Commands.Migrations
{
    [DbContext(typeof(InsuranceCommandDbContext))]
    partial class InsuranceCommandDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Insurance.AppCore.Domain.Parvandes.Entities.Lost", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AccidentDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("AccidentLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AppraiserBusinessKey")
                        .HasColumnType("uuid");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<Guid>("BusinessKey")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityBusinessKey")
                        .HasColumnType("uuid");

                    b.Property<byte?>("ClaimType")
                        .HasColumnType("smallint");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InspectionAddress")
                        .HasColumnType("text");

                    b.Property<string>("InspectionCity")
                        .HasColumnType("text");

                    b.Property<long>("LostClaimantInfoId")
                        .HasColumnType("bigint");

                    b.Property<string>("LostNumber")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedByUserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PolicyHolder")
                        .HasColumnType("text");

                    b.Property<string>("PolicyNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("ProvinceBusinessKey")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReportDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("LostClaimantInfoId");

                    b.ToTable("Losts");
                });

            modelBuilder.Entity("Insurance.AppCore.Domain.Parvandes.Entities.LostClaimantInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("BusinessKey")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CarSystemAndTipBusinessKey")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<byte>("Gender")
                        .HasColumnType("smallint");

                    b.Property<byte>("GroupHeadType")
                        .HasColumnType("smallint");

                    b.Property<Guid>("InsuranceCompanyBranch")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InsuranceCompanyBusinessKey")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LostBusinessKey")
                        .HasColumnType("uuid");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedByUserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<byte>("PlateModelType")
                        .HasColumnType("smallint");

                    b.Property<string>("PolicyHolderFullName")
                        .HasColumnType("text");

                    b.Property<string>("VehiclePlate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VehiclePlateDesign")
                        .HasColumnType("integer");

                    b.Property<byte>("VehiclePlateType")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("LostClaimantInfos");
                });

            modelBuilder.Entity("Insurance.AppCore.Domain.Parvandes.Entities.Lost", b =>
                {
                    b.HasOne("Insurance.AppCore.Domain.Parvandes.Entities.LostClaimantInfo", "LostClaimantInfo")
                        .WithMany()
                        .HasForeignKey("LostClaimantInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LostClaimantInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
